<a href="https://colab.research.google.com/github/arnabghorui/smai_project/blob/main/SMAI_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TF IDF & MLP

Here we are given two articles and we have to check similarity between them,
There are many metrics of similarity, <br>
<br>
One of them is TF IDF ( Total Frequency * Inverse Document Frequency). In this metric we multiply the number of times a word is present in a document to the inverse of the number of the articles that the word appears in. The inverse part shows the overall importance of the word and the frequency part shows how important the given word is in the context of the present article. <br>
<br>


###Loading the data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import json
f = open('/content/drive/MyDrive/Colab Notebooks/Project/train_data.json')
train_data = json.load(f)
g= open('/content/drive/MyDrive/Colab Notebooks/Project/test_data.json')
test_data = json.load(g)

In [3]:
print(test_data[0].keys())

print(len(test_data))

dict_keys(['pair_id', 'title_1', 'title_2', 'text_1', 'text_2', 'tags_1', 'tags_2', 'meta_lang_1', 'meta_lang_2', 'score'])
4316


After Filtering out the english articles - we compare the two articles in a given element. 

For that we append the two articles with keys : text_1 and text_2 

In [4]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from string import punctuation


# english_articles_train = []
# english_articles_test = []

all_articles_train = []
all_articles_test = []



# for d in train_data:
#   if d['meta_lang_1'] == 'en' and d['meta_lang_2'] == 'en':
#     english_articles_train.append(d)

# for d in test_data:
#   if d['meta_lang_1'] == 'en' and d['meta_lang_2'] == 'en':
#     english_articles_test.append(d)

for d in train_data:
  all_articles_train.append(d)

for d in test_data:
  all_articles_test.append(d)

total_train_articles = []
total_test_articles = []

y_train = []
y_test = []

# for eng in english_articles_train:
#   total_train_articles.append(eng['text_1'])
#   total_train_articles.append(eng['text_2'])
#   y_train.append(eng['score'])

# for eng in english_articles_test:
#   total_test_articles.append(eng['text_1'])
#   total_test_articles.append(eng['text_2'])
#   y_test.append(eng['score'])


for article in all_articles_train:
  total_train_articles.append(article['text_1'])
  total_train_articles.append(article['text_2'])
  y_train.append(article['score'])

for article in all_articles_test:
  total_test_articles.append(article['text_1'])
  total_test_articles.append(article['text_2'])
  y_test.append(article['score'])

'''
art1 = art1.split()

art2 = art2.split()

for i in range(len(art1)):
    art1[i] = ''.join([letter for letter in art1[i] if letter not in punctuation])

for i in range(len(art2)):
    art2[i] = ''.join([letter for letter in art2[i] if letter not in punctuation])
'''

#########################################################



tf = TfidfVectorizer(min_df =4)

x_train = tf.fit(total_train_articles)
x_train = tf.transform(total_train_articles)
x_test = tf.transform(total_test_articles)


print('x_train shape:  '+  str(x_train.shape))

print(type(x_train))



X_text_1_train = []
X_text_2_train = []
X_text_1_test = []
X_text_2_test = []


print('x_test shape:  '+  str(x_test.shape))



# for j in range(1287):
#   X_text_1_train.append(x_train[2*j])
#   X_text_2_train.append(x_train[2*j+1])

# for j in range(236):
#   X_text_1_test.append(x_test[2*j])
#   X_text_2_test.append(x_test[2*j+1])

for j in range(2857):
  X_text_1_train.append(x_train[2*j])
  X_text_2_train.append(x_train[2*j+1])

for j in range(4316):
  X_text_1_test.append(x_test[2*j])
  X_text_2_test.append(x_test[2*j+1])

x_train shape:  (5714, 35012)
<class 'scipy.sparse.csr.csr_matrix'>
x_test shape:  (8632, 35012)


In [5]:
from scipy.sparse import csr_matrix
 

X1_train = []
X2_train = []
X1_test = []
X2_test = []

# for i in range(1287):
for i in range(2857):
  X1_train.append(np.array(csr_matrix.todense(X_text_1_train[i])))
  X2_train.append(np.array(csr_matrix.todense(X_text_2_train[i])))

# for i in range(236):
for i in range(4316):
  X1_test.append(np.array(csr_matrix.todense(X_text_1_test[i])))
  X2_test.append(np.array(csr_matrix.todense(X_text_2_test[i])))


y_train = np.array(y_train)
y_test = np.array(y_test)

# #scor1 = np.reshape(scor1,(1287,1))
# X1_train = np.array(X1_train)
# X2_train = np.array(X2_train)
# X1_test = np.array(X1_test)
# X2_test = np.array(X2_test)

# #rows1 = np.reshape()

# X1_train = X1_train.reshape(1287,25972)
# X2_train = X2_train.reshape(1287,25972)
# X1_test = X1_test.reshape(236,25972)
# X2_test = X2_test.reshape(236,25972)

#########################################

#scor1 = np.reshape(scor1,(1287,1))
X1_train = np.array(X1_train)
X2_train = np.array(X2_train)
X1_test = np.array(X1_test)
X2_test = np.array(X2_test)

#rows1 = np.reshape()


X1_train = X1_train.reshape(2857,35012)
X2_train = X2_train.reshape(2857,35012)
X1_test = X1_test.reshape(4316,35012)
X2_test = X2_test.reshape(4316,35012)



#Model

This is the Siamese implementation of the 

In [6]:
from tensorflow import keras
from keras.models import Model
from keras.layers import Dense, LSTM, Input, concatenate

# input_1 = Input(shape=(25972, ))
input_1 = Input(shape=(35012, ))
dense_1 = Dense(1000, )(input_1)

# input_2 = Input(shape=(25972, ))
input_2 = Input(shape=(35012, ))
dense_2 = Dense(1000, )(input_2)

merge = concatenate([dense_1, dense_2])

dense_3  = Dense(200,)(merge)
dense_4  = Dense(50,)(dense_3)
dense_all = Dense(1,)(dense_4)
#second_dense = Dense(2, activation='softmax')(merge)

model1 = Model(inputs=[input_1, input_2], outputs=dense_all)
optimizer = keras.optimizers.Adam()  #learning_rate=0.001
model1.compile(loss='mse', optimizer = optimizer) #, metrics=['RootMeanSquaredError']
print(model1.summary())

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 35012)]      0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, 35012)]      0           []                               
                                                                                                  
 dense (Dense)                  (None, 1000)         35013000    ['input_1[0][0]']                
                                                                                                  
 dense_1 (Dense)                (None, 1000)         35013000    ['input_2[0][0]']                
                                                                                              

#Model 2
Model Changed from concatenate(dense1, dense2) to (desnse1+dense2, dense1-dense2)

In [7]:
from tensorflow import keras
from keras.models import Model
from keras.layers import Dense, LSTM, Input, concatenate

# input_1 = Input(shape=(25972, ))
input_1 = Input(shape=(35012, ))
dense_1 = Dense(1000, )(input_1)

# input_2 = Input(shape=(25972, ))
input_2 = Input(shape=(35012, ))
dense_2 = Dense(1000, )(input_2)

merge = concatenate([dense_1+dense_2, dense_1-dense_2])

dense_3  = Dense(200,)(merge)
dense_4  = Dense(50,)(dense_3)
dense_all = Dense(1,)(dense_4)
#second_dense = Dense(2, activation='softmax')(merge)

model2 = Model(inputs=[input_1, input_2], outputs=dense_all)
optimizer = keras.optimizers.Adam()  #learning_rate=0.001
model2.compile(loss='mse', optimizer = optimizer) #, metrics=['RootMeanSquaredError']
print(model2.summary())

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, 35012)]      0           []                               
                                                                                                  
 input_4 (InputLayer)           [(None, 35012)]      0           []                               
                                                                                                  
 dense_5 (Dense)                (None, 1000)         35013000    ['input_3[0][0]']                
                                                                                                  
 dense_6 (Dense)                (None, 1000)         35013000    ['input_4[0][0]']                
                                                                                            

In [8]:
history1 = model1.fit([X1_train, X2_train], y_train, epochs=10)
history2 = model2.fit([X1_train, X2_train], y_train, epochs=10,validation_split=0.1)

Epoch 1/10
90/90 [==============================] - 5s 21ms/step - loss: 1.6295
Epoch 2/10
90/90 [==============================] - 2s 24ms/step - loss: 0.3897
Epoch 3/10
90/90 [==============================] - 2s 21ms/step - loss: 0.1237
Epoch 4/10
90/90 [==============================] - 2s 21ms/step - loss: 0.0591
Epoch 5/10
90/90 [==============================] - 2s 21ms/step - loss: 0.0511
Epoch 6/10
90/90 [==============================] - 2s 21ms/step - loss: 0.0555
Epoch 7/10
90/90 [==============================] - 2s 21ms/step - loss: 0.0635
Epoch 8/10
90/90 [==============================] - 2s 21ms/step - loss: 0.0616
Epoch 9/10
90/90 [==============================] - 2s 21ms/step - loss: 0.0908
Epoch 10/10
90/90 [==============================] - 2s 21ms/step - loss: 0.0972
Epoch 1/10
81/81 [==============================] - 2s 24ms/step - loss: 1.6909 - val_loss: 1.8292
Epoch 2/10
81/81 [==============================] - 2s 22ms/step - loss: 0.3901 - val_loss: 1.3349
E

In [9]:
y_pred_1 = model1.predict([X1_test,X2_test])
y_pred_2 = model2.predict([X1_test,X2_test])

135/135 [==============================] - 1s 7ms/step


In [10]:
print(y_pred_1)
print(y_pred_2)

[[2.4455829]
 [1.9306217]
 [2.3525124]
 ...
 [1.5918281]
 [1.5918281]
 [1.8711962]]
[[2.4055734]
 [2.594357 ]
 [3.3667316]
 ...
 [1.5998698]
 [1.5998698]
 [1.7349164]]


In [11]:
'''
import numpy as np


y_pred_new_1 = []
y_pred_new_2 = []
fractions = np.array([0, 0.25, 0.333333, 0.5, 0.666666667, 0.75, 1])

for i in range(len(y_pred)):
  error1 = y_pred_1[i] - int(y_pred_1[i])
  error2 = y_pred_2[i] - int(y_pred_2[i])
  # print(error)
  minArg = np.argmin(abs(fractions - error))
  y_pred_new_1.append( int(y_pred_1[i])+ fractions[minArg])
  y_pred_new_2.append( int(y_pred_2[i])+ fractions[minArg])


print(y_pred_new_1)
print(y_pred_new_2)

'''


'\nimport numpy as np\n\n\ny_pred_new_1 = []\ny_pred_new_2 = []\nfractions = np.array([0, 0.25, 0.333333, 0.5, 0.666666667, 0.75, 1])\n\nfor i in range(len(y_pred)):\n  error1 = y_pred_1[i] - int(y_pred_1[i])\n  error2 = y_pred_2[i] - int(y_pred_2[i])\n  # print(error)\n  minArg = np.argmin(abs(fractions - error))\n  y_pred_new_1.append( int(y_pred_1[i])+ fractions[minArg])\n  y_pred_new_2.append( int(y_pred_2[i])+ fractions[minArg])\n\n\nprint(y_pred_new_1)\nprint(y_pred_new_2)\n\n'

In [12]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.feature_selection import r_regression
print('Model 1')
print('The mean absolute error for the model is ', mean_absolute_error(y_test,y_pred_1))
print('The mean squared error for the model is ', mean_squared_error(y_test,y_pred_1))
print('Model 2')
print('The mean absolute error for the model is ', mean_absolute_error(y_test,y_pred_2))
print('The mean squared error for the model is ', mean_squared_error(y_test,y_pred_2))

Model 1
The mean absolute error for the model is  1.1147355851445406
The mean squared error for the model is  1.700139522599828
Model 2
The mean absolute error for the model is  1.0981071168556233
The mean squared error for the model is  1.6572023268108187


In [13]:
from scipy.stats import pearsonr

print(pearsonr(y_test,y_pred_1))
print(pearsonr(y_test,y_pred_2))

(array([0.022859541954517316], dtype=object), 0.13321392040705035)
(array([0.014873496957733576], dtype=object), 0.3286165419093739)


In [16]:
y_pred_2_train = model2.predict([X1_train,X2_train])
print(pearsonr(y_train,y_pred_2_train))

90/90 [==============================] - 1s 7ms/step
(array([0.9042880520925023], dtype=object), 0.0)
